# -*- encoding: utf-8 -*-
# Generated by jeweler

Gem::Specification.new do |s|
  s.name = %q{dm-postgis}	  
  s.version = "2.0.0"	
  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roman Kamyk jr","svs"]
  s.description = %q{Adds DMGeometry type to DataMapper that uses GeoRuby for (de)serializing Geometry types into Postgis.}
  s.email = %q{roman.kamyk@gmail.com svs@svs.io}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "dm-postgis.gemspec",
    "lib/dm-postgis.rb",
    "lib/dm-postgis/pg_geometry.rb",
    "spec/pg_geometry_spec.rb",
  ]
  s.homepage = %q{http://github.com/rkj/dm-postgis}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Geometry type for DataMapper}
  s.test_files = [
    "spec/pg_geometry_spec.rb",
  ]

  dm_version = "~>1.2.0"
  s.add_dependency "GeoRuby", "1.3.4"
  s.add_runtime_dependency "rake"
  s.add_runtime_dependency "dm-core", dm_version
  s.add_runtime_dependency "dm-postgres-adapter", dm_version
  s.add_development_dependency "dm-migrations", dm_version
  s.add_development_dependency "rspec", "~>2.6.0"
  s.add_development_dependency "debugger"
end

