# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-postgis}
  s.version = "1.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roman Kamyk jr"]
  s.date = %q{2010-11-16}
  s.description = %q{Adds DMGeometry type to DataMapper that uses GeoRuby for (de)serializing Geometry types into Postgis}
  s.email = %q{roman.kamyk@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "dm-postgis.gemspec",
    "lib/dm-postgis-adapter.rb",
    "lib/dm-postgis.rb",
    "lib/postgis_adapter.rb",
    "spec/dummy.rb",
    "spec/fixtures/geo.rb"
  ]
  s.homepage = %q{http://github.com/rkj/dm-postgis}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Geometry type for DataMapper}
  s.test_files = [
    "spec/dummy.rb",
    "spec/fixtures/geo.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<GeoRuby>, ["= 1.3.4"])
      s.add_runtime_dependency(%q<dm-core>, ["= 1.0.2"])
      s.add_runtime_dependency(%q<dm-postgres-adapter>, ["= 1.0.2"])
    else
      s.add_dependency(%q<GeoRuby>, ["= 1.3.4"])
      s.add_dependency(%q<dm-core>, ["= 1.0.2"])
      s.add_dependency(%q<dm-postgres-adapter>, ["= 1.0.2"])
    end
  else
    s.add_dependency(%q<GeoRuby>, ["= 1.3.4"])
    s.add_dependency(%q<dm-core>, ["= 1.0.2"])
    s.add_dependency(%q<dm-postgres-adapter>, ["= 1.0.2"])
  end
end

